import openpyxl as op
import datetime
import os
import platform
import pymysql
import pyodbc
import time

############################################################### 기본 변수 세팅
# 현재 실행 위치 담기
gtm_filepos = os.getcwd()

# 오늘날짜 세팅
gtm_now = datetime.datetime.now().strftime('%Y-%m-%d')

# 플랫폼 담기
gtm_platform = platform.system()

gtm_splitdef = ''

# 필요한 파일들 여기에다 위치시키기
if gtm_platform == 'Windows':
    gtm_filepos = gtm_filepos + '\\BK\\FILE\\'
    gtm_splitdef = '\\'
else:
    gtm_filepos = gtm_filepos + '/BK/FILE/'
    gtm_splitdef = '/'

os.putenv('NLS_LANG', '.UTF8')

tableList = [
# "BK_ACN_INFO_T",
# "BK_ACN_MNG_T",
# "BK_ACN_MSG_T",
# "BK_ACN_PRO_T",
# "BK_ACN_REQ_T",
# "BK_ACN_TDF_T",
# "BK_APP_LOGIN_T",
# "BK_APP_VERSION_T",
# "BK_AT_LGN_T",
# "BK_AUTH_ACD_T",
# "BK_AUTH_AMF_T",
# "BK_AUTH_MCD_T",
# "BK_AUTH_MFM_T",
# "BK_AUTH_MNGR_T",
# "BK_AU_CON_T",
# "BK_AU_HIS_T",
# "BK_AU_MNG_T",
# "BK_BAD_BYR_T",
# "BK_BR_APPLY_T",
# "BK_BR_MNG_T",
# "BK_BYR_SPAM_REPORT",
# "BK_BZ_BYR_APPL_T",
# "BK_BZ_BYR_BOOTH_T",
# "BK_BZ_BYR_EMP_HIS_T",
# "BK_BZ_BYR_ITEM_T",
# "BK_BZ_CORP_APPL_T",
# "BK_BZ_CORP_ATND_T",
# "BK_BZ_CORP_BOOTH_T",
# "BK_BZ_CORP_ITEM_T",
# "BK_BZ_CORP_REQ_T",
# "BK_BZ_HIS_T",
# "BK_BZ_MIG_BAT_HIS_T",
# "BK_BZ_MIG_LOCK_T",
# "BK_BZ_PLAN_DEPEND_T",
# "BK_BZ_PLAN_FILE_T",
"BK_BZ_PLAN_T"
# "BK_BZ_SURV_ITEM_DTL_T",
# "BK_BZ_SURV_ITEM_GROUP_T",
# "BK_BZ_SURV_ITEM_T",
# "BK_BZ_SURV_RST_T",
# "BK_BZ_SURV_T",
# "BK_CAT_HS_T",
# "BK_CAT_SUM_T",
# "BK_CC_LWP_T",
# "BK_CC_UPP_T",
# "BK_CE_DET_T",
# "BK_CE_MNG_T",
# "BK_CE_PAC_T",
# "BK_CH_GROUP_T",
# "BK_CH_INVIT_T",
# "BK_CH_MSG_T",
# "BK_CM_AMM_T",
# "BK_CM_AMR2_T",
# "BK_CM_AUR2_T",
# "BK_CM_BUYER",
# "BK_CM_BUYER_DATA",
# "BK_CM_BUYER_OPN",
# "BK_CM_CHM_T",
# "BK_CM_CNT_T",
# "BK_CM_COD_T",
# "BK_CM_CORP_INTRCN",
# "BK_CM_DMS_T",
# "BK_CM_NOTE_T",
# "BK_CM_ZIN_T",  # 데이터가 너무 많아 제외
# "BK_CM_ZIO_T",
# "BK_CN_BUY_T",
# "BK_CN_FILE_INFO_T",
# "BK_CN_MNG_T",
# "BK_CN_OFE_T",
# "BK_CN_PAR_T",
# "BK_CN_PUR_T",
# "BK_CN_SEL_T",
# "BK_COM_PSWD_CHK_T",
# "BK_CONT_CD_T",
# "BK_CO_DIA_T",
# "BK_CO_EXP_T",
# "BK_CO_MLG_T",
# "BK_CRM_EXPDECL_T",
# "BK_CR_EXP_T",
# "BK_CR_INC_T",
# "BK_CR_MNG_T",
# "BK_CR_NAT_T",
# "BK_CR_UPL_T",
# "BK_CS_NOT_T",
# "BK_CS_POP_T",
# "BK_CS_VOA_T",
# "BK_CS_VOC_T",
# "BK_CUR_MNG_T",
# "BK_CUST_MEM_T",
# "BK_DG_BUY_T",
# "BK_DG_GOD_T",
# "BK_DG_GOO_T",
# "BK_DG_KTC_T",
# "BK_DG_MNG_T",
# "BK_DG_PAR_T",
# "BK_DG_PUR_T",
# "BK_DG_SEL_T",
# "BK_DG_TIM_T",
# "BK_DL_DET_T",
# "BK_DL_DHL_T",
# "BK_DL_LOG_T",
# "BK_DL_MNG_T",
# "BK_DL_STT_T",
# "BK_DSPY_CAT_MNG_T",
# "BK_DT_TEMP_T",
# "BK_ECA_INF_T",
# "BK_EG_RESULT",
# "BK_EG_RST",
# "BK_EMS_ACMSLT_T",
# "BK_EM_FORM_T",
# "BK_EM_LOG_T",
# "BK_EM_TMP_T",
# "BK_EN_CNSLT_LANG",
# "BK_EN_EXP_HOPE_NAT",
# "BK_EN_MBE_SUB_OWN_T",
# "BK_EN_MBE_SUB_T",
# "BK_EN_MBE_T",
# "BK_EN_MNFTR_FCLTY",
# "BK_ES_DET_T",
# "BK_ES_MNG_T",
# "BK_ES_MNG_T_BAK",
# "BK_EX_MNG_T",
# "BK_FA_ANS_T",
# "BK_FA_CAT_T",
# "BK_FA_MNG_T",
# "BK_FA_QDS_T",
# "BK_FA_QES_T",
# "BK_FX_ALL_T",
# "BK_FX_FIT_T",
# "BK_FX_TIM_T",
# "BK_GEODB_HISTORY_T",
# "BK_GO_APV_HIST",
# "BK_GO_CAPA_T",
# "BK_GO_CNT_T",
# "BK_GO_CONFM_HIS_T",
# "BK_GO_FILE_T",
# "BK_GO_MNG_AUL_T",
# "BK_GO_MNG_AUT_HALAL_T",
# "BK_GO_MNG_AUT_T",
# "BK_GO_MNG_ON",
# "BK_HP_MNG_T",
# "BK_IM_STT_T",
# "BK_KP_PRT_T",
# "BK_LINK_ACT_T",
# "BK_LINK_HIST_T",
# "BK_LINK_TBL_T",
# "BK_MA_EMP_T",
# "BK_MA_INFO_T",
# "BK_MA_INF_T",
# "BK_MA_MAP_T",
# "BK_MA_NOT_T",
# "BK_MEM_LOG_T",
# "BK_ME_BYR_T_SECSN",
# "BK_ME_HIS_T",
# "BK_MLG_LOG_T",
# "BK_MLG_MNG_LOG_T",
# "BK_MLG_MNG_T",
# "BK_NOTE_RECPTN_T",
# "BK_NOTE_SEND_T",
# "BK_OB_RESULT",
# "BK_OB_RST",
# "BK_OF_APV_T",
# "BK_OF_CNT_T",
# "BK_OF_FAV_T",
# "BK_OF_HIST_T",
# "BK_OF_MNG_T",
# "BK_PA_CAT_GO_T",
# "BK_PA_CAT_T",
# "BK_PA_EX_MAP_T",
# "BK_PA_GOG_GO_T",
# "BK_PA_GOG_T",
# "BK_PA_IG_MAP_T",
# "BK_PA_IG_MNG_T",
# "BK_PA_MNG_T",
# "BK_PA_PAR_T",
# "BK_PA_PAR_TMP_T",
# "BK_PA_VOA_T",
# "BK_PA_VOC_T",
# "BK_PC_ADV_T",
# "BK_PC_MBE_T",
# "BK_PC_TMP_T",
# "BK_PG_LOG_T",
# "BK_PO_BYR_NEW_T",
# "BK_PP_GOG_T",
# "BK_PP_INV_DLVY_T",
# "BK_PP_INV_T",
# "BK_PP_LOG_T",
# "BK_PSH_DVC_T",
# "BK_PSH_SND_T",
# "BK_PSH_STT_T",
# "BK_PSH_T",
# "BK_REP_SEL_T",
# "BK_SE_DET_T",
# "BK_SE_HIS_T",
# "BK_SE_LOG_T",
# "BK_SE_MNG_T",
# "BK_SM_LOG_T",
# "BK_SM_TMP_T",
# "BK_STATS_BYR_MA_T",
# "BK_STATS_CNTT_T",
# "BK_STATS_CORP_RGN_T",
# "BK_STATS_EMS_CNT_T",
# "BK_STATS_GD_CAT_T",
# "BK_STATS_GD_INQ_T",
# "BK_STATS_GD_RGN_T",
# "BK_STATS_INQ_OF_T",
# "BK_STATS_KOPS_CAT_T",
# "BK_STATS_KOPS_CNTT_T",
# "BK_STATS_KOPS_CNT_T",
# "BK_STATS_KOPS_MA_T",
# "BK_STATS_OF_CAT_T",
# "BK_STATS_OF_MA_T",
# "BK_STRT_LOG",
# "BK_TEST_DIS",
# "BK_TRADE_TRANS",
# "BK_TRD_TLK_FND_T",
# "BK_TRD_TLK_HIS_T",
# "BK_TR_APPROVED_EXT_T",
# "BK_TR_DET_FILE_T",
# "BK_TT_GOG_T",
# "BK_TT_INV_T",
# "BK_TT_LOG_T",
# "BK_TT_MNG_T",
# "BK_TT_ORD_DET_T",
# "BK_TT_ORD_T",
# "BK_VD_CONFR_T",
# "BK_VT_LOG_T",
# "BK_WIZELOG_HIS_T",
# "BK_WIZELOG_PAGE_T",
# "COMTCCMMNCLCODE",
# "COMTCZIP",
# "COMTECOPSEQ",
# "COMTHEMAILDSPTCHMANAGE",
# "COMTHPROGRMCHANGEDTLS",
# "COMTNAUTHORGROUPINFO",
# "COMTNAUTHORINFO",
# "COMTNAUTHORROLERELATE",
# "COMTNBKMKMENUMANAGERESULT",
# "COMTNEMPLYRINFO",
# "COMTNEMPLYRSCRTYESTBS",
# "COMTNENTRPRSMBER",
# "COMTNFILE",
# "COMTNFILEDETAIL",
# "COMTNGNRLMBER",
# "COMTNLOGINPOLICY",
# "COMTNMENUCREATDTLS",
# "COMTNMENUINFO",
# "COMTNORGNZTINFO",
# "COMTNPROGRMLIST",
# "COMTNRESTDE",
# "COMTNROLEINFO",
# "COMTNROLES_HIERARCHY",
# "COMTNSITEMAP",
# "COMTRDNMADRZIP",
# "CRM_BR_LINE",
# "CRM_BR_LINE_ITEM",
# "CRM_BR_LINE_TRD",
# "CRM_BR_RST",
# "CRM_BS_LINE",
# "CRM_BS_LINE_ATND",
# "CRM_BS_LINE_TRD",
# "CRM_BS_LINE_TRDITEM",
# "CRM_BS_RST",
# "CRM_CM_BUYER",
# "CRM_CM_BUYER_EMP",
# "CRM_CM_BUYER_ITEM",
# "CRM_CM_CORP",
# "CRM_CM_CORP_SPC",
# "CRM_CM_CUST",
# "CRM_CM_CUST_REL",
# "CRM_CM_EXIMCORP_TOTAL",
# "CRM_CM_EXIMHIST_COUNTRY",
# "CRM_CM_EXIMHIST_YEAR",
# "CRM_CO_BIZCODE",
# "CRM_CO_CONV_CODE",
# "CRM_CO_COUNTRY",
# "CRM_CO_DEPT",
# "CRM_CO_ECATALOG",
# "CRM_CO_HSCODE",
# "CRM_CO_KISLINE",
# "CRM_CO_ORD_HEADER",
# "CRM_CO_STTL",
# "CRM_CO_USER",
# "CRM_EF_LINE",
# "CRM_EF_LINE_ATND",
# "CRM_EF_LINE_ITEM",
# "CRM_EF_PLAN",
# "CRM_EF_RST",
# "CRM_EF_TIMETBL",
# "CRM_EG_PLAN",
# "CRM_EG_PROD",
# "CRM_EG_RESULT",
# "CRM_EG_RST",
# "CRM_EX_LINE",
# "CRM_EX_LINE2",
# "CRM_EX_LINE_ATND",
# "CRM_EX_LINE_CNSL",
# "CRM_EX_LINE_ITEM",
# "CRM_EX_PLAN",
# "CRM_EX_PLAN2",
# "CRM_OB_BIZINFO",
# "CRM_OB_BIZRST",
# "CRM_PT_LINE",
# "CRM_PT_LINEATND",
# "CRM_PT_PLAN",
# "CRM_PT_TIMETBL",
# "CRM_RA_LINE",
# "CRM_RA_LINE2",
# "CRM_RA_LINE2_DTL",
# "CRM_RA_LINE3",
# "CRM_RA_LINE_BUYER",
# "CRM_RA_LINE_ITEM",
# "CRM_SM_COMMCODE",
# "CRM_SM_FILEINFO",
# "CRM_TM_LINE",
# "CRM_TM_LINE_ATND",
# "CRM_TM_LINE_TRD",
# "CRM_TM_LINE_TRDITEM",
# "CRM_TM_PLAN",
# "CRM_TM_PLAN_TRD",
# "CRM_TM_RST",
# "CRM_VC_VOC",
# "CRM_VC_VOCPROC",
# "CRM_WC_CHAMP",
# "CRM_WC_RST",
# "GOODS_INTRL_LIST_TEMP",
# "GOODS_INTRL_TEMP",
# "IM_DMAIL_CLICK_17",
# "IM_DMAIL_CLICK_22",
# "IM_DMAIL_CLICK_6",
# "IM_DMAIL_INFO_17",
# "IM_DMAIL_INFO_22",
# "IM_DMAIL_INFO_23",
# "IM_DMAIL_INFO_6",
# "IM_DMAIL_INFO_AUX_17",
# "IM_DMAIL_INFO_AUX_22",
# "IM_DMAIL_INFO_AUX_6",
# "IM_DMAIL_QUERY_17",
# "IM_DMAIL_QUERY_22",
# "IM_DMAIL_QUERY_6",
# "IM_DMAIL_TEMPLATE_17",
# "IM_DMAIL_TEMPLATE_22",
# "IM_DMAIL_TEMPLATE_6",
# "IM_ENC_DMAIL_17",
# "IM_ENC_DMAIL_22",
# "IM_ENC_DMAIL_6",
# "IM_RESULT_CLICK",
# "IM_RESULT_CLICK_INFO",
# "IM_RESULT_INFO",
# "IM_RESULT_REJECT",
# "IM_RESULT_SEND",
# "IM_RESULT_SITE",
# "IM_RESULT_SITE_INFO",
# "IM_RESULT_STAT",
# "KH_CM_AGM2_T",
# "KH_CM_AGMM2_T",
# "KH_CM_AMMM2_T",
# "KH_CM_AMM_T",
# "KH_CM_AMR2_T",
# "KH_CM_AUR2_T",
# "KH_CM_DOM_T",
# "KH_CM_LBM_T",
# "KH_CM_MNU_T",
# "KH_CM_MSG_T",
# "KH_CM_SUR_T",
# "MATCH_LOGIN_LOG",
# "MIG_LOG",
# "MIG_LOG_CODE_CHECK",
# "MK_AUTH_AMF_T",
# "MK_AUTH_MCD_T",
# "MK_BY_BLOCK_SCHD_T",
# "MK_BY_BLOCK_TIME_T",
# "MK_BY_PATH_T",
# "MK_BY_PREF_TIME_T",
# "MK_BY_SPOT_APPL_T",
# "MK_BY_SPOT_ITEM_T",
# "MK_BY_STAY_FILE_HIS_T",
# "MK_BY_STAY_FILE_T",
# "MK_BY_STAY_FILE_WAIT_T",
# "MK_BY_STAY_SCHD_HIS_T",
# "MK_BY_STAY_SCHD_T",
# "MK_BY_STAY_SCHD_WAIT_T",
# "MK_CM_COD_T",
# "MK_CM_COPY_T",
# "MK_CN_AGENT_EMP_T",
# "MK_CN_AGENT_T",
# "MK_CN_APPL_HIS_T",
# "MK_CN_APPL_T",
# "MK_CN_AUTH_HRCH_T",
# "MK_CN_AUTH_MENU_T",
# "MK_CN_AUTH_ROLE_T",
# "MK_CN_AUTH_T",
# "MK_CN_AUTH_USER_T",
# "MK_CN_BIZ_AGENT_T",
# "MK_CN_BIZ_RST_T",
# "MK_CN_BOOTH_T",
# "MK_CN_BRCST_MAIL_LOG_T",
# "MK_CN_BRCST_SMS_LOG_T",
# "MK_CN_MATCH_SCHD_HIS_T",
# "MK_CN_MATCH_SCHD_T",
# "MK_CN_MENU_T",
# "MK_CN_MNG_HIS_T",
# "MK_CN_MNG_T",
# "MK_CN_NOTI_FILE_T",
# "MK_CN_NOTI_T",
# "MK_CN_PUSH_DTL_T",
# "MK_CN_PUSH_EVENT_T",
# "MK_CN_PUSH_LOG_T",
# "MK_CN_PUSH_MNG_T",
# "MK_CN_QNA_T",
# "MK_CN_ROLE_T",
# "MK_CN_SCHD_GROUP_T",
# "MK_CN_SCHD_TIME_T",
# "MK_CN_SURV_ITEM_DTL_T",
# "MK_CN_SURV_ITEM_T",
# "MK_CN_SURV_RST_T",
# "MK_CN_SURV_T",
# "MK_CN_USER_T",
# "MK_CO_BLOCK_SCHD_HIS_T",
# "MK_CO_BLOCK_SCHD_T",
# "MK_CO_BLOCK_TIME_T",
# "MK_CO_PATH_T",
# "MK_CO_PREF_TIME_T",
# "MK_CO_SPOT_APPL_T",
# "MK_CO_SPOT_ITEM_T",
# "MK_CO_STAY_FILE_HIS_T",
# "MK_CO_STAY_FILE_T",
# "MK_CO_STAY_FILE_WAIT_T",
# "MK_CO_STAY_SCHD_HIS_T",
# "MK_CO_STAY_SCHD_T",
# "MK_CO_STAY_SCHD_WAIT_T",
# "MK_PB_BASE_SURV_ITEM_DTL_T",
# "MK_PB_BASE_SURV_ITEM_T",
# "MK_PB_NOTI_FILE_T",
# "MK_PB_NOTI_T",
# "MK_PB_QNA_T",
# "MK_PB_SURV_ITEM_DTL_T",
# "MK_PB_SURV_ITEM_T",
# "MK_PB_SURV_RST_T",
# "MK_PB_SURV_T",
# "SC_TRAN",
# "TB_AUTH_HIST",
# "TB_BKBUYER_APLY_CMDLT_INFO",
# "TB_BKCNTT_CD_INFO",
# "TB_BK_BADN_BUYER_IP_INFO",
# "TB_BK_BIZ_APLY_TRIPER_INFO",
# "TB_BK_BUYER_BIZ_APLY",
# "TB_BK_BUYER_INFO_READNG_HIST",
# "TB_BK_BUYER_MAIN_EXPSR_ECPT_GOODS",
# "TB_BK_BUYER_MAIN_GOODS",
# "TB_BK_BYBIZ_ATFILE_MNT",
# "TB_BK_BYBUYR_BTH",
# "TB_BK_BYSITE_FAQ_CTGRY_MNT",
# "TB_BK_CITY_INFO",
# "TB_BK_CMMN_CD",
# "TB_BK_CMMN_FILE_STOR_INFO",
# "TB_BK_CNTT_CD_INFO",
# "TB_BK_CPBIZ_INFO",
# "TB_BK_CREDT_BADN_EXPTER_MNT",
# "TB_BK_CREDT_BADN_OVRSS_MNT",
# "TB_BK_CREDT_BADN_UPLOAD",
# "TB_BK_CSTMR_CNTER_UPPER_CTGRY",
# "TB_BK_DCOMP_BIZ_APLY",
# "TB_BK_DCOMP_BIZ_APLY_KBC_REQ",
# "TB_BK_DHL_DLVY_MNT",
# "TB_BK_DLVY_DTL",
# "TB_BK_DLVY_MNT",
# "TB_BK_DMSTC_REGN_CD",
# "TB_BK_ECNMY_DPLM_INTRCN",
# "TB_BK_EMAIL_SNDNG_FOM",
# "TB_BK_ENTP_ADIT_INFO",
# "TB_BK_ENTP_ADIT_INFO_PSSN_STTUS",
# "TB_BK_ENTP_MBER_ADIT_INFO",
# "TB_BK_ETC_BIZ_SPRT_BRKDWN",
# "TB_BK_EXBI_MAIN_MAPNG",
# "TB_BK_EXPGW_SPRT_BRKDWN",
# "TB_BK_FAQ_MNT",
# "TB_BK_GOODS_IMG_UPLOAD_PERM",
# "TB_BK_GOODS_SALE_SITE",
# "TB_BK_GOODS_SHIPNG_EXPEC_REGN",
# "TB_BK_GO_CNFM_HIST_INFO",
# "TB_BK_GO_IMG_MNT_INFO",
# "TB_BK_GO_IMG_UPLOAD_PERM_INFO",
# "TB_BK_GO_MVP_INFO",
# "TB_BK_GO_PRC_INFO",
# "TB_BK_GO_SALE_SITE_INFO",
# "TB_BK_GO_SHIPNG_EXPEC_REGN_INFO",
# "TB_BK_GO_TRSPT_CND_INFO",
# "TB_BK_GO_TRSPT_MTH_INFO",
# "TB_BK_HALAL_BYCERT_NAT_INFO",
# "TB_BK_INVC_GOODS",
# "TB_BK_INVC_LOG",
# "TB_BK_INVC_MNT",
# "TB_BK_KBC_CHRGR",
# "TB_BK_KBC_NAT_MAPNG",
# "TB_BK_KBC_SITE_MNT",
# "TB_BK_KOPS_ISSU",
# "TB_BK_KOPS_SETLE_LOG",
# "TB_BK_LRGE_CPCT_EMAIL_LIST_INFO",
# "TB_BK_MAIN_EXPSR_ECPT_GOODS_INFO",
# "TB_BK_MVP_CNSLT_REQ_BRKDWN",
# "TB_BK_NAT_CD",
# "TB_BK_NAT_CRTFC_INFO",
# "TB_BK_NOTE_RCV_MNT",
# "TB_BK_NOTE_SND_MNT",
# "TB_BK_OENTP_INFO",
# "TB_BK_OF_CTGRY_INFO",
# "TB_BK_ONLN_PAVLN_CTGRY",
# "TB_BK_ONLN_PAVLN_CTGRY_GOODS",
# "TB_BK_ONLN_PAVLN_GOODS",
# "TB_BK_ONLN_PAVLN_GOODS_GROUP",
# "TB_BK_OVRSS_MBER",
# "TB_BK_OVRSS_MBER_CNFM_HIST",
# "TB_BK_PAVLN_MNT",
# "TB_BK_PAVLN_PTCP_GOODS",
# "TB_BK_PAVLN_UPT_EXPSR_INFO",
# "TB_BK_PA_GOODS_BANR_INDICT_INFO",
# "TB_BK_PA_UPT_INDICT_INFO",
# "TB_BK_PCHRG_MBER_HIST",
# "TB_BK_PRQUDO_DTL",
# "TB_BK_PRQUDO_MNT",
# "TB_BK_PYPAL_ERROR",
# "TB_BK_SELLER_LAST_LOGIN_INFO",
# "TB_BK_SETLE_DTL_MNT",
# "TB_BK_SMS_LOG",
# "TB_BK_SND_LRGE_CPCT_EMAIL_INFO",
# "TB_BK_SPCLTY_MFCMM_MNT",
# "TB_BK_STATS_BUYER_BYKBC",
# "TB_BK_STATS_BYCNTT",
# "TB_BK_STATS_BYOFFR_CTGRY",
# "TB_BK_STATS_DENTP_BYRGN",
# "TB_BK_STATS_DENTP_EMS_SETLE",
# "TB_BK_STATS_KOPS_ESTMT_SETLE",
# "TB_BK_STATS_KOPS_SETLE_BYCNTT",
# "TB_BK_STATS_KOPS_SETLE_BYKBC",
# "TB_BK_STATS_KOPS_SETLE_CTGRY",
# "TB_BK_STATS_RCV_SND_INQRY_BYBOFR",
# "TB_BK_STATS_RCV_SND_INQRY_BYCOMP",
# "TB_BK_UNTY_LWPRT_PAVLN_REL_MNT",
# "TB_BK_UNTY_PAVLN_MNT",
# "TB_BK_USER_EMAIL_LIST_INFO",
# "TB_BK_USER_PWD_ERROR_MNT",
# "TB_BK_USER_SND_ADRES_STOR_INFO",
# "TB_BK_VOC_ANS_MNT",
# "TB_BK_VOC_QSTN_MNT",
# "TB_CE_DLVY_MNT_INFO",
# "TB_CE_DLVY_PKG_MNT_INFO",
# "TB_TT_INVC_GOODS_INFO",
# "TB_TT_INVC_LOG_INFO",
# "TB_TT_INVC_MNT_INFO",
# "TB_TT_MNT_INFO",
# "TB_TT_ORDER_BRKDWN_DTL_INFO",
# "TB_TT_ORDER_BRKDWN_INFO"
]

tabErr = []

############################################################### 데이터베이스 연결
# 티베로 연동
print("==================> 티베로 연결 테스트")
# gtm_Tconn  = pyodbc.connect(DSN='DATAWARE',UID='BKUSER',PWD='KOTRABK')
# gtm_Tcur  = gtm_Tconn.cursor()
gtm_Tconn  = pyodbc.connect(DSN='DATAWARE',UID='bknanal',PWD='kotra123!')
gtm_Tcur  = gtm_Tconn.cursor()

# 마리아 DB연동
print("=================> 마리아 연결 테스트")
# gtm_Mconn = pymysql.connect(host='180.100.215.207',port=13306, user='root', 
#                        password='mariadb2022!', db='db_bk', charset='utf8')

gtm_Mconn = pymysql.connect(host='192.168.50.125',port=3306, user='bkuser', 
                       password='1234', db='bkuser', charset='utf8')

gtm_Mcur = gtm_Mconn.cursor()



############################################################### 티베로 데이터 가져오기 및 컬럼개수 세팅
# 티베로 테이블 값 리스트에 담기
print("=================> 티베로 데이터 가져오기")
startT = time.time()

for tab in tableList:
    try:
        gtm_Tcur.execute("SELECT * FROM BKUSER."+ tab)
        gtm_Trows = gtm_Tcur.fetchall()
        gtm_Trows2 = []

        for row in gtm_Trows:
            gtm_Trows2.append(tuple(row))
        print("==========>" + tab)


        # 마리에 넣을 인서트 구문 넣기
        print("=================> 마리아에 넣기 위한 인서트 구문 만들기")
        colCount = len(gtm_Trows2[0])
        gtm_Tinsert = "INSERT INTO bkuser."+tab+" VALUES("
        for item in range(0,colCount):
            gtm_Tinsert =gtm_Tinsert+"%s,"
        gtm_Tinsert = gtm_Tinsert[0:-1] +")"


        ############################################################## 마리아에 티베로 데이터 넣기
        print("=================> 마리아 데이터 인서트")
        gtm_Mcur.executemany(gtm_Tinsert, gtm_Trows2)
        gtm_Mconn.commit()
    except:
        tabErr.append(tab)
        continue


    ############################################################## 마리아에 티베로 데이터 넣기
    print("=================> 마리아 데이터 인서트")
    gtm_Mcur.executemany(gtm_Tinsert, gtm_Trows2)
    gtm_Mconn.commit()


gtm_Tconn.close()
gtm_Mconn.close()

print("=================> 티베로에 테이블 없는 것 또는 오류")
for err in tabErr:
    print(err)

print("time : ", time.time() - startT)